"""add patient portal fields

Revision ID: 3626f42ee110
Revises: 7a08d1be7478
Create Date: 2026-05-05 13:50:15.866786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3626f42ee110'
down_revision = '7a08d1be7478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('betreuer_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('portal_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('portal_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('portal_sprache', sa.String(length=5), nullable=True))
        batch_op.create_unique_constraint(None, ['portal_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('portal_sprache')
        batch_op.drop_column('portal_enabled')
        batch_op.drop_column('portal_token')
        batch_op.drop_column('betreuer_email')

    # ### end Alembic commands ###
