"""fuhrpark phase 2 wartungsprotokoll fuehrerschein

Revision ID: 4daa807bb1f3
Revises: 8bc83fcd3f59
Create Date: 2026-05-06 11:09:02.992132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4daa807bb1f3'
down_revision = '8bc83fcd3f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wartungsprotokoll',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('fahrzeug_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('art', sa.String(length=30), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('werkstatt', sa.String(length=200), nullable=True),
    sa.Column('km_stand', sa.Integer(), nullable=True),
    sa.Column('kosten', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('naechster_termin', sa.Date(), nullable=True),
    sa.Column('naechste_km', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['fahrzeug_id'], ['fahrzeuge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wartungsprotokoll', schema=None) as batch_op:
        batch_op.create_index('ix_wartungsprotokoll_datum', ['datum'], unique=False)
        batch_op.create_index('ix_wartungsprotokoll_fahrzeug_id', ['fahrzeug_id'], unique=False)

    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuehrerschein_klasse', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('fuehrerschein_bis', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employees', schema=None) as batch_op:
        batch_op.drop_column('fuehrerschein_bis')
        batch_op.drop_column('fuehrerschein_klasse')

    with op.batch_alter_table('wartungsprotokoll', schema=None) as batch_op:
        batch_op.drop_index('ix_wartungsprotokoll_fahrzeug_id')
        batch_op.drop_index('ix_wartungsprotokoll_datum')

    op.drop_table('wartungsprotokoll')
    # ### end Alembic commands ###
