"""Add procedure schedule visitreport and schedulegeneration models

Revision ID: 7a08d1be7478
Revises: 007
Create Date: 2026-05-04 21:48:14.549610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7a08d1be7478'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('required_qualification', sa.String(length=100), nullable=True),
    sa.Column('requires_verification', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.create_index('ix_procedures_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_procedures_is_active', ['is_active'], unique=False)

    op.create_table('schedule_generations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('schedule_start_date', sa.Date(), nullable=False),
    sa.Column('schedule_end_date', sa.Date(), nullable=False),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('ai_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('distributed_at', sa.DateTime(), nullable=True),
    sa.Column('distributed_to_count', sa.Integer(), nullable=True),
    sa.Column('schedules_created', sa.Integer(), nullable=True),
    sa.Column('anonymize_for_ai', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_generations', schema=None) as batch_op:
        batch_op.create_index('ix_schedule_generations_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_schedule_generations_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_schedule_generations_status', ['status'], unique=False)

    op.create_table('visit_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('visit_start_time', sa.DateTime(), nullable=False),
    sa.Column('visit_end_time', sa.DateTime(), nullable=True),
    sa.Column('procedures_completed', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.Column('patient_condition', sa.String(length=100), nullable=True),
    sa.Column('issues_encountered', sa.Text(), nullable=True),
    sa.Column('photo_ids', sa.Text(), nullable=True),
    sa.Column('verification_method', sa.String(length=30), nullable=True),
    sa.Column('device_mac', sa.String(length=17), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('signature_confirmed', sa.Boolean(), nullable=True),
    sa.Column('signature_time', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('billable_minutes', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('visit_reports', schema=None) as batch_op:
        batch_op.create_index('ix_visit_reports_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_visit_reports_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_visit_reports_patient_id', ['patient_id'], unique=False)
        batch_op.create_index('ix_visit_reports_status', ['status'], unique=False)
        batch_op.create_index('ix_visit_reports_visit_date', ['visit_date'], unique=False)

    op.create_table('employee_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time', sa.Time(), nullable=False),
    sa.Column('procedures', sa.Text(), nullable=True),
    sa.Column('address_strasse', sa.String(length=255), nullable=True),
    sa.Column('address_hausnummer', sa.String(length=20), nullable=True),
    sa.Column('address_plz', sa.String(length=10), nullable=True),
    sa.Column('address_ort', sa.String(length=100), nullable=True),
    sa.Column('patient_geo_lat', sa.Float(), nullable=True),
    sa.Column('patient_geo_lng', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alerts', sa.Text(), nullable=True),
    sa.Column('visit_report_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['visit_report_id'], ['visit_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_schedules', schema=None) as batch_op:
        batch_op.create_index('ix_employee_schedules_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_employee_schedules_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_employee_schedules_patient_id', ['patient_id'], unique=False)
        batch_op.create_index('ix_employee_schedules_scheduled_date', ['scheduled_date'], unique=False)
        batch_op.create_index('ix_employee_schedules_status', ['status'], unique=False)

    with op.batch_alter_table('employee_locations', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('employee_patient_assignments', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'PRIMARY_NURSE'::character varying"))
        batch_op.alter_column('assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_employee_patient_assignments_company_id'))
        batch_op.drop_index(batch_op.f('ix_employee_patient_assignments_employee_id'))
        batch_op.drop_index(batch_op.f('ix_employee_patient_assignments_patient_id'))

    with op.batch_alter_table('medication_documents', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    with op.batch_alter_table('patient_photos', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_patient_photos_is_active'))
        batch_op.create_index('ix_patient_photos_employee_id', ['employee_id'], unique=False)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('care_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'HOME_CARE'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.alter_column('care_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'HOME_CARE'::character varying"))

    with op.batch_alter_table('patient_photos', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_photos_employee_id')
        batch_op.create_index(batch_op.f('ix_patient_photos_is_active'), ['is_active'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('medication_documents', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('employee_patient_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_patient_assignments_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_patient_assignments_employee_id'), ['employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_employee_patient_assignments_company_id'), ['company_id'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('assigned_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'PRIMARY_NURSE'::character varying"))

    with op.batch_alter_table('employee_locations', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('employee_schedules', schema=None) as batch_op:
        batch_op.drop_index('ix_employee_schedules_status')
        batch_op.drop_index('ix_employee_schedules_scheduled_date')
        batch_op.drop_index('ix_employee_schedules_patient_id')
        batch_op.drop_index('ix_employee_schedules_employee_id')
        batch_op.drop_index('ix_employee_schedules_company_id')

    op.drop_table('employee_schedules')
    with op.batch_alter_table('visit_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_visit_reports_visit_date')
        batch_op.drop_index('ix_visit_reports_status')
        batch_op.drop_index('ix_visit_reports_patient_id')
        batch_op.drop_index('ix_visit_reports_employee_id')
        batch_op.drop_index('ix_visit_reports_company_id')

    op.drop_table('visit_reports')
    with op.batch_alter_table('schedule_generations', schema=None) as batch_op:
        batch_op.drop_index('ix_schedule_generations_status')
        batch_op.drop_index('ix_schedule_generations_created_by')
        batch_op.drop_index('ix_schedule_generations_company_id')

    op.drop_table('schedule_generations')
    with op.batch_alter_table('procedures', schema=None) as batch_op:
        batch_op.drop_index('ix_procedures_is_active')
        batch_op.drop_index('ix_procedures_company_id')

    op.drop_table('procedures')
    # ### end Alembic commands ###
