"""add fuhrpark tables

Revision ID: 8bc83fcd3f59
Revises: a57a595c3ee7
Create Date: 2026-05-06 10:58:11.665577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bc83fcd3f59'
down_revision = 'a57a595c3ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fahrzeuge',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kennzeichen', sa.String(length=20), nullable=False),
    sa.Column('marke', sa.String(length=50), nullable=True),
    sa.Column('modell', sa.String(length=100), nullable=True),
    sa.Column('baujahr', sa.Integer(), nullable=True),
    sa.Column('farbe', sa.String(length=30), nullable=True),
    sa.Column('kraftstoff', sa.String(length=20), nullable=True),
    sa.Column('fahrgestellnummer', sa.String(length=50), nullable=True),
    sa.Column('tuev_bis', sa.Date(), nullable=True),
    sa.Column('versicherung_bis', sa.Date(), nullable=True),
    sa.Column('versicherung_nr', sa.String(length=50), nullable=True),
    sa.Column('versicherung_gesellschaft', sa.String(length=100), nullable=True),
    sa.Column('km_stand', sa.Integer(), nullable=True),
    sa.Column('km_stand_datum', sa.Date(), nullable=True),
    sa.Column('anschaffungsdatum', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fahrzeuge', schema=None) as batch_op:
        batch_op.create_index('ix_fahrzeuge_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_fahrzeuge_status', ['status'], unique=False)

    op.create_table('kilometerbuch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('fahrzeug_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('km_start', sa.Integer(), nullable=False),
    sa.Column('km_end', sa.Integer(), nullable=False),
    sa.Column('abfahrt_ort', sa.String(length=200), nullable=True),
    sa.Column('ziel_ort', sa.String(length=200), nullable=True),
    sa.Column('zweck', sa.String(length=30), nullable=True),
    sa.Column('kraftstoff_kosten', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('kraftstoff_liter', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('bemerkungen', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['fahrzeug_id'], ['fahrzeuge.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kilometerbuch', schema=None) as batch_op:
        batch_op.create_index('ix_kilometerbuch_datum', ['datum'], unique=False)
        batch_op.create_index('ix_kilometerbuch_employee_id', ['employee_id'], unique=False)
        batch_op.create_index('ix_kilometerbuch_fahrzeug_id', ['fahrzeug_id'], unique=False)

    op.create_table('schadensmeldungen',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('fahrzeug_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('ort', sa.String(length=200), nullable=True),
    sa.Column('versicherung_gemeldet', sa.Boolean(), nullable=True),
    sa.Column('reparatur_kosten', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['fahrzeug_id'], ['fahrzeuge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schadensmeldungen', schema=None) as batch_op:
        batch_op.create_index('ix_schadensmeldungen_fahrzeug_id', ['fahrzeug_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schadensmeldungen', schema=None) as batch_op:
        batch_op.drop_index('ix_schadensmeldungen_fahrzeug_id')

    op.drop_table('schadensmeldungen')
    with op.batch_alter_table('kilometerbuch', schema=None) as batch_op:
        batch_op.drop_index('ix_kilometerbuch_fahrzeug_id')
        batch_op.drop_index('ix_kilometerbuch_employee_id')
        batch_op.drop_index('ix_kilometerbuch_datum')

    op.drop_table('kilometerbuch')
    with op.batch_alter_table('fahrzeuge', schema=None) as batch_op:
        batch_op.drop_index('ix_fahrzeuge_status')
        batch_op.drop_index('ix_fahrzeuge_company_id')

    op.drop_table('fahrzeuge')
    # ### end Alembic commands ###
