"""add patient_greetings table

Revision ID: a57a595c3ee7
Revises: e0f93b495ad9
Create Date: 2026-05-05 15:16:21.037513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57a595c3ee7'
down_revision = 'e0f93b495ad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_greetings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('occasion', sa.String(length=200), nullable=False),
    sa.Column('occasion_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sent_email', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_greetings', schema=None) as batch_op:
        batch_op.create_index('ix_patient_greetings_company_id', ['company_id'], unique=False)
        batch_op.create_index('ix_patient_greetings_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_patient_greetings_patient_id', ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_greetings', schema=None) as batch_op:
        batch_op.drop_index('ix_patient_greetings_patient_id')
        batch_op.drop_index('ix_patient_greetings_created_at')
        batch_op.drop_index('ix_patient_greetings_company_id')

    op.drop_table('patient_greetings')
    # ### end Alembic commands ###
