"""add arzt portal fields to patient

Revision ID: e0f93b495ad9
Revises: 3626f42ee110
Create Date: 2026-05-05 14:09:39.226125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f93b495ad9'
down_revision = '3626f42ee110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medication_plans', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arzt_token', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('arzt_portal_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('arzt_last_update', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['arzt_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('arzt_last_update')
        batch_op.drop_column('arzt_portal_enabled')
        batch_op.drop_column('arzt_token')

    with op.batch_alter_table('medication_plans', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###
